### ISSUE TITLE
t3v compiles but panicked at 'called `Result::unwrap()` on an `Err` value: InvalidImage', src/main.rs:130:65

### ISSUE THREAD

**Issue by ajmcello** [dr-bonez/tor-v3-vanity#14]
Latest version
Latest nightly
cargo: cargo 1.62.0-nightly (e2e2ddd 2022-04-05)
rustc 1.62.0-nightly (90ca44752 2022-04-11)
kernel: 5.15.0-25-generic
(Ubuntu)

| NVIDIA-SMI 510.60.02    Driver Version: 510.60.02    CUDA Version: 11.6     |

Errors:

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidImage', src/main.rs:130:65
stack backtrace:
   0:     0x55eb0aa71d2d - std::backtrace_rs::backtrace::libunwind::trace::hda39d6860b2d6f70
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55eb0aa71d2d - std::backtrace_rs::backtrace::trace_unsynchronized::ha1bfdeb508735a0a
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55eb0aa71d2d - std::sys_common::backtrace::_print_fmt::h4e9e937d66742a36
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55eb0aa71d2d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h73a948c4553c4f51
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55eb0aa9229c - core::fmt::write::ha91e2a0e6cdcb7d1
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/core/src/fmt/mod.rs:1194:17
   5:     0x55eb0aa6f3d1 - std::io::Write::write_fmt::heda409ac36864e96
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/io/mod.rs:1655:15
   6:     0x55eb0aa73635 - std::sys_common::backtrace::_print::he8c3809f69ea2342
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55eb0aa73635 - std::sys_common::backtrace::print::hecbd7b926628aa09
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55eb0aa73635 - std::panicking::default_hook::{{closure}}::h8fbf7884094b6f2e
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:295:22
   9:     0x55eb0aa732a9 - std::panicking::default_hook::h6334d4a28312e99b
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:314:9
  10:     0x55eb0aa73bd2 - std::panicking::rust_panic_with_hook::h73dbf64f0060aa58
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:698:17
  11:     0x55eb0aa73ab7 - std::panicking::begin_panic_handler::{{closure}}::h57f62f8b0c4aa3d9
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:588:13
  12:     0x55eb0aa721e4 - std::sys_common::backtrace::__rust_end_short_backtrace::h3194a80099ffb120
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55eb0aa737e9 - rust_begin_unwind
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:584:5
  14:     0x55eb0a9c6db3 - core::panicking::panic_fmt::h77eb0c9a0a627689
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/core/src/panicking.rs:142:14
  15:     0x55eb0a9c6ea3 - core::result::unwrap_failed::h64c030d5f199bf09
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/core/src/result.rs:1785:5
  16:     0x55eb0a9ca39c - std::sys_common::backtrace::__rust_begin_short_backtrace::hac7684f292823293
  17:     0x55eb0a9ce131 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hef3fd462c2778518
  18:     0x55eb0aa763b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha7e881609c254b01
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/alloc/src/boxed.rs:1858:9
  19:     0x55eb0aa763b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4d60f6af39e55bd7
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/alloc/src/boxed.rs:1858:9
  20:     0x55eb0aa763b3 - std::sys::unix::thread::Thread::new::thread_start::h69dc955aa1b43699
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys/unix/thread.rs:108:17
  21:     0x7f52f5185b43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  22:     0x7f52f5217a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  23:                0x0 - <unknown>
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/main.rs:thread '296<unnamed>:' panicked at '32called `Result::unwrap()` on an `Err` value: RecvError
', src/main.rs:stack backtrace:
273:40
   0:     0x55eb0aa71d2d - std::backtrace_rs::backtrace::libunwind::trace::hda39d6860b2d6f70
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55eb0aa71d2d - std::backtrace_rs::backtrace::trace_unsynchronized::ha1bfdeb508735a0a
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55eb0aa71d2d - std::sys_common::backtrace::_print_fmt::h4e9e937d66742a36
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55eb0aa71d2d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h73a948c4553c4f51
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55eb0aa9229c - core::fmt::write::ha91e2a0e6cdcb7d1
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/core/src/fmt/mod.rs:1194:17
   5:     0x55eb0aa6f3d1 - std::io::Write::write_fmt::heda409ac36864e96
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/io/mod.rs:1655:15
   6:     0x55eb0aa73635 - std::sys_common::backtrace::_print::he8c3809f69ea2342
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55eb0aa73635 - std::sys_common::backtrace::print::hecbd7b926628aa09
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55eb0aa73635 - std::panicking::default_hook::{{closure}}::h8fbf7884094b6f2e
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:295:22
   9:     0x55eb0aa732a9 - std::panicking::default_hook::h6334d4a28312e99b
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:314:9
  10:     0x55eb0aa73bd2 - std::panicking::rust_panic_with_hook::h73dbf64f0060aa58
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:698:17
  11:     0x55eb0aa73ab7 - std::panicking::begin_panic_handler::{{closure}}::h57f62f8b0c4aa3d9
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:588:13
  12:     0x55eb0aa721e4 - std::sys_common::backtrace::__rust_end_short_backtrace::h3194a80099ffb120
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55eb0aa737e9 - rust_begin_unwind
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:584:5
  14:     0x55eb0a9c6db3 - core::panicking::panic_fmt::h77eb0c9a0a627689
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/core/src/panicking.rs:142:14
  15:     0x55eb0a9c6ea3 - core::result::unwrap_failed::h64c030d5f199bf09
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/core/src/result.rs:1785:5
  16:     0x55eb0a9d37f3 - t3v::main::hac55a96cacc0a366
  17:     0x55eb0a9c9c53 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4b2a1858060f0322
  18:     0x55eb0a9cd619 - std::rt::lang_start::{{closure}}::hd2893dcfcd14f530
  19:     0x55eb0aa6ad4e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h8747dac316cfe8b1
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/core/src/ops/function.rs:280:13
  20:     0x55eb0aa6ad4e - std::panicking::try::do_call::ha8cfd36c99c35841
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:492:40
  21:     0x55eb0aa6ad4e - std::panicking::try::h44599ca0771bc4e2
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:456:19
  22:     0x55eb0aa6ad4e - std::panic::catch_unwind::hfc289307f73cb8b7
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panic.rs:137:14
  23:     0x55eb0aa6ad4e - std::rt::lang_start_internal::{{closure}}::h9fadec4e4222aa5a
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/rt.rs:128:48
  24:     0x55eb0aa6ad4e - std::panicking::try::do_call::h742ca90b47c7614a
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:492:40
  25:     0x55eb0aa6ad4e - std::panicking::try::ha8060cd5fe01b8e1
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:456:19
  26:     0x55eb0aa6ad4e - std::panic::catch_unwind::h3548704cd9c5e356
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panic.rs:137:14
  27:     0x55eb0aa6ad4e - std::rt::lang_start_internal::hc6526c5151dc66ec
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/rt.rs:128:20
  28:     0x55eb0a9d3922 - main
  29:     0x7f52f511ad90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  30:     0x7f52f511ae40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  31:     0x55eb0a9c7055 - _start
  32:                0x0 - <unknown>
stack backtrace:
   0:     0x55eb0aa71d2d

**Comment by vivekvpandya** [comment]
make sure:
1) It is being run on NV GPU
2) NVGPU must support PTX and CUDA. (Install CUDA if not already).

```
            // Load PTX module
            let module_data = CString::new(include_str!(env!("KERNEL_PTX_PATH"))).unwrap();
            let kernel = Module::load_from_string(&module_data).unwrap();
```
based on the error it seems following module load is failing so if all above points are correct then better to debug this point and see why things are failing.

**Comment by lt3stus3el** [comment]
Where is the PTX kernel in ubuntu?

What should I set as ```KERNEL_PTX_PATH```?
